-- Migration 008: Remove simulated TX/AZ records from competitor_analysis
-- These were inserted by extractSimulated() in run_historical_90d.js (now removed).
-- The function generated permit numbers like TX-123456-0 ... TX-123456-599 on every run,
-- bypassing deduplication and accumulating ~1,200 fake records per daily cron execution.
-- Safe to run multiple times (DELETE WHERE is idempotent once records are gone).

-- Remove all TX and AZ records (not in MultiVenza scope)
DELETE FROM competitor_analysis WHERE state IN ('TX', 'AZ');

-- Remove GA simulated records only (pattern: GA-NNNNNN-N generated by Date.now())
-- Real GA records from Accela/EnerGov have different permit number formats.
DELETE FROM competitor_analysis
WHERE state = 'GA'
  AND permit_number ~ '^GA-\d{6,}-\d+$';

-- Fix leads with state=null (FL leads from Hillsborough inserted before state was required)
-- Wimauma/Riverview/Lithia are all in Hillsborough County, FL
UPDATE leads
SET state = 'FL'
WHERE state IS NULL
  AND county IS NOT DISTINCT FROM 'Hillsborough'
     OR (state IS NULL AND city IN ('Wimauma','Riverview','Lithia','Sun City Center','Ruskin','Apollo Beach','Brandon','Valrico'));

-- Fallback: any remaining null state with FL zip codes (33xxx range used by Hillsborough)
UPDATE leads
SET state = 'FL'
WHERE state IS NULL
  AND zip_code LIKE '33%';

-- Report remaining counts
SELECT state, COUNT(*) AS remaining
FROM competitor_analysis
GROUP BY state
ORDER BY state;

SELECT state, COUNT(*) AS leads_by_state
FROM leads
GROUP BY state
ORDER BY state;
